In [1]:
import numpy as np

In [4]:
a= np.array([1,2,3])

In [5]:
a[0]

1

Three benifit of using numpy array is
1. Less Meomory
2. Fast
3. Convinient`

In [7]:
import sys
l = range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [8]:
array = np.array(1000)
print(array.size*array.itemsize)

8


In [13]:
SIZE = 100000

l1 = range(SIZE)
l2 = range(SIZE)


In [14]:
a1 = np.array(SIZE)
a2 = np.array(SIZE)

In [15]:
import time
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print((time.time() - start)*1000)

25.639772415161133


In [16]:
start = time.time()
result = a1+ a2
print((time.time() - start)*1000)

1.9078254699707031


Basic Operations

In [17]:
a = np.array([5,6,9])

In [18]:
a[0]

5

In [21]:
a = np.array([[1,2],[3,4],[5,6]])

In [22]:
#This will the dimension of the array 
a.ndim


2

In [23]:
a.itemsize

8

In [24]:
a.dtype

dtype('int64')

In [25]:
a = np.array([[1,2],[3,4],[5,6]],dtype=np.float64)

In [26]:
a.dtype

dtype('float64')

In [27]:
a.size

6

In [28]:
a.shape

(3, 2)

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
#it will create a array of a specific range
np.arange(1,5)

array([1, 2, 3, 4])

In [34]:
np.arange(1,5,2)

array([1, 3])

In [36]:
#this will generate number between the range and distributing in linearly
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [37]:
a.shape

(3, 2)

In [38]:
a.reshape(2,3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
#This will flaten by array in a single line 
#This will not make changes in the original array it will create a seperate a new array
a.ravel()

array([1., 2., 3., 4., 5., 6.])

In [41]:
a.min()

1.0

In [42]:
a.max()

6.0

In [43]:
a.sum()

21.0

In [44]:
#axis =0 is columns
#axis =1 is row
a.sum(axis=0)

array([ 9., 12.])

In [45]:
a.sum(axis=1)

array([ 3.,  7., 11.])

In [46]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [47]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [48]:
a+b

array([[ 6,  8],
       [10, 12]])

In [49]:
a*b

array([[ 5, 12],
       [21, 32]])

In [50]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [51]:
a.dot(b)

array([[19, 22],
       [43, 50]])

1. Indexing and slicing
2. Iterating through array
3. Stacking together two array
4. Indexing with boolean array

In [52]:
a = np.array([6,7,8])

In [53]:
a[0:2]

array([6, 7])

In [54]:
a[-1]

8

In [55]:
b = np.array([[6,7,8],[1,2,3],[9,3,2]])

In [56]:
b


array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [58]:
b[1,2]

3

In [59]:
b[0:2,2]

array([8, 3])

In [60]:
b[-1]

array([9, 3, 2])

In [61]:
b[-1,0:2]

array([9, 3])

In [62]:
b[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [63]:
b

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [64]:
for row in b :
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [66]:
for cell in b.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [67]:
a = np.arange(6,12).reshape(3,2)
b = np.arange(6).reshape(3,2)


In [68]:
a

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [69]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [70]:
#This will stack two different araay on each other
np.vstack((a,b))

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5]])

In [71]:
#In this the stacking is done horizontally
#two array combine to each 
np.hstack((a,b))

array([[ 6,  7,  0,  1],
       [ 8,  9,  2,  3],
       [10, 11,  4,  5]])

In [72]:
a = np.arange(30).reshape(2,15)

In [73]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [75]:
result = np.hsplit(a,3)

In [76]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [77]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [79]:
#This split which we did above we can also do it with vertical using vsplit

In [80]:
a = np.arange(12).reshape(3,4)

In [81]:
b = a >4

In [82]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [83]:
# this will help elimate the records which we don't want in our dataset
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [84]:
a[b] = -1

In [85]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [87]:
a = np.arange(12).reshape(3,4)

In [88]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [90]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [95]:
for x in np.nditer(a,order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [97]:
for x in np.nditer(a,order='F',flags =['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [98]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...] = x*x

In [99]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [100]:
b = np.arange(3,15,4).reshape(3,1)

In [101]:
b

array([[ 3],
       [ 7],
       [11]])

In [102]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
